version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: topfotos_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senhaforte123
      POSTGRES_DB: topfotosdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Os scripts na pasta database/ rodarão apenas na PRIMEIRA inicialização para criar as tabelas e dados falsos
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - topfotos_net

  backend:
    build:
      context: ./backend
    container_name: topfotos_backend
    restart: always
    environment:
      PORT: 3001
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senhaforte123
      POSTGRES_DB: topfotosdb
      POSTGRES_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - topfotos_net

  frontend:
    build:
      context: .
    container_name: topfotos_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - topfotos_net

volumes:
  pgdata:

networks:
  topfotos_net:
